apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app: {{ .Release.Name }}
imagePullSecrets:
  - name: {{ .Values.serviceAccount.imagePullSecret }}
