deployment:
  replicas: 1
  image:
    repository: shawnweigand/prod
    tag: portfolio
  probes:
    enabled: true
  registry:
    imagePullSecret: docker-registry-secret
serviceAccount:
  name: docker-registry-serviceaccount
  imagePullSecret: docker-registry-secret

ingress:
  host: shawnweigand.com
  tls: true
  externalPort: 80
  internalPort: 8080

issuer:
  email: weigandshawn@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory

pdb:
  minAvailable: 1

config:
  APP_NAME: "Shawn Weigand"
  APP_URL: https://shawnweigand.com
  APP_ENV: production
  SESSION_DRIVER: cookie
  MAIL_MAILER: failover
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: 587
  MAIL_USERNAME: shawnweigandapps@gmail.com
  MAIL_ENCRYPTION: tls
  MAIL_FROM_ADDRESS: shawn@shawnweigand.com
  MAIL_FROM_NAME: "${APP_NAME}"
  MAIL_TO_ADDRESS: shawn@shawnweigand.com
  MAIL_TO_NAME: "Shawn Weigand"
  MAILGUN_DOMAIN: shawnweigand.com
  QUEUE_CONNECTION: redis
  REDIS_CLIENT: phpredis
  REDIS_PORT: 6379
