deployment:
  replicas: 1
  image:
    repository: shawnweigand/prod
    tag: portfolio
  registry:
    imagePullSecret: docker-registry-secret
serviceAccount:
  name: docker-registry-serviceaccount
  imagePullSecret: docker-registry-secret

ingress:
  host: shawnweigand.com
  tls: true

issuer:
  email: weigandshawn@gmail.com
  server: https://acme-v02.api.letsencrypt.org/directory

pdb:
  minAvailable: 1

config:
  APP_NAME: "Shawn Weigand"
  APP_URL: https://shawnweigand.com
  APP_ENV: production
  SESSION_DRIVER: array
  MAIL_MAILER: smtp
  MAIL_HOST: smtp.gmail.com
  MAIL_PORT: 587
  MAIL_USERNAME: shawnweigandapps@gmail.com
  MAIL_ENCRYPTION: tls
  MAIL_FROM_NAME: "${APP_NAME}"
  MAIL_FROM_ADDRESS: weigandshawn@gmail.com

