name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  # test:
  #   needs: checkout
  #   uses: shawnweigand/devops/.github/workflows/testflow.yml@main
  #   with:
  #     example-input: "Hello, TestFlow!"

  build:
    needs: checkout
    uses: shawnweigand/devops/.github/workflows/docker.yml@main
    with:
      tag: portfolio
    secrets: inherit

  approve:
    needs: build
    uses: shawnweigand/devops/.github/workflows/approve.yml@main
    with:
      environment: production

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: approval
  #   steps:
  #   - name: Install doctl
  #     uses: digitalocean/action-doctl@v2
  #     with:
  #       token: ${{ secrets.DO_API_TOKEN }}
  #   - name: Save DigitalOcean kubeconfig
  #     run: doctl kubernetes cluster kubeconfig save k8s-do-prod-nyc1-weigandshawn
  #   - name: Helm tool installer
  #     uses: azure/setup-helm@v4.2.0
  #   - name: List directory structure
  #     run: |
  #       ls -R
  #   - name: Deploy Helm chart to DOKS
  #     run: |
  #       helm upgrade --install portfolio ./helm \
  #       --set image.repository="${{ secrets.DOCKER_USERNAME }}/prod" \
  #       --set image.tag="portfolio" \
  #       --namespace portfolio
