name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ vars.DOCKER_USERNAME }}/prod:portfolio

  approval:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production   # Replace with your environment name
    steps:
    - name: Wait for manual approval
      run: echo "Manual approval required for deployment."

  deploy:
    runs-on: ubuntu-latest
    needs: approval
    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_TOKEN }}
    - name: Save DigitalOcean kubeconfig
      run: doctl kubernetes cluster kubeconfig save k8s-do-prod-nyc1-weigandshawn
    - name: Helm tool installer
      uses: azure/setup-helm@v4.2.0
    - name: Deploy Helm chart to DOKS
      run: |
        helm upgrade --install portfolio ../../helm \
        --set image.repository="${{ secrets.DOCKER_USERNAME }}/prod" \
        --set image.tag="portfolio" \
        --namespace portfolio
